services:
  mongodb:
    image: mongo:7
    pull_policy: if_not_present
    container_name: embrava-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: embrava-sensors
    restart: unless-stopped

volumes:
  mongodb_data:
